package marcowidesott.CapstoneBE.entities;

public enum Asset {
    EUR_USD, USD_JPY, GBP_USD, AUD_USD, USD_CAD, EUR_GBP, EUR_JPY, NZD_USD, USD_CHF, USD_CNY,
    BTC_USD, ETH_USD, LTC_USD, XRP_USD, DOGE_USD, ADA_USD, DOT_USD, SOL_USD, AVAX_USD, MATIC_USD,
    SP500, NASDAQ, DOWJONES, FTSE100, NIKKEI, HANGSENG, CAC40, DAX, ASX200, SENSEX, RTS,
    GOLD_USD, SILVER_USD, WTI_OIL, BRENT_OIL, COPPER_USD, PLATINUM_USD, PALLADIUM_USD, COFFEE_USD,
    SUGAR_USD, COCOA_USD, WHEAT_USD, CORN_USD, RICE_USD, SOYBEANS_USD, OAT_USD, SUGAR_CANE_USD, LUMBER_USD,
    CAD_USD, CHF_USD, GBP_JPY
}
